;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Attack",DevComment="")
+GameplayTagList=(Tag="Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Action.Swap",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")
+GameplayTagList=(Tag="Weapon.Gun",DevComment="")
+GameplayTagList=(Tag="Weapon.Magic",DevComment="")
+GameplayTagList=(Tag="Weapon.Sword",DevComment="")

